2020-06-04 01:00:53.1359 ERROR В методе: Void PrepareToSaveChanges(System.Data.Entity.Core.Objects.SaveOptions) возникло исключение: Операция завершилась с ошибкой. Не удалось изменить связь, поскольку один или несколько свойств внешнего ключа не допускают значения NULL. При изменении связи соответствующему свойству внешнего ключа присваивается значение NULL. Если внешний ключ не поддерживает значений NULL, должна быть определена новая связь, свойству внешнего ключа должно быть присвоено другое значение, отличное от NULL, либо необходимо удалить несвязанный объект.
2020-06-04 01:17:12.7191 ERROR В методе: Void PrepareToSaveChanges(System.Data.Entity.Core.Objects.SaveOptions) возникло исключение: Операция завершилась с ошибкой. Не удалось изменить связь, поскольку один или несколько свойств внешнего ключа не допускают значения NULL. При изменении связи соответствующему свойству внешнего ключа присваивается значение NULL. Если внешний ключ не поддерживает значений NULL, должна быть определена новая связь, свойству внешнего ключа должно быть присвоено другое значение, отличное от NULL, либо необходимо удалить несвязанный объект.
2020-06-04 01:22:40.9875 ERROR В методе: Void PrepareToSaveChanges(System.Data.Entity.Core.Objects.SaveOptions) возникло исключение: Операция завершилась с ошибкой. Не удалось изменить связь, поскольку один или несколько свойств внешнего ключа не допускают значения NULL. При изменении связи соответствующему свойству внешнего ключа присваивается значение NULL. Если внешний ключ не поддерживает значений NULL, должна быть определена новая связь, свойству внешнего ключа должно быть присвоено другое значение, отличное от NULL, либо необходимо удалить несвязанный объект.
2020-06-04 14:45:48.2974 ERROR В методе: System.Data.Common.DbConnection get_Connection() возникло исключение: Экземпляр ObjectContext был удален и больше не может использоваться в операциях, требующих соединения.
2020-06-04 14:46:05.7959 ERROR В методе: Int32 SaveChanges() возникло исключение: При обновлении записей возникла ошибка. Дополнительные сведения приведены во внутреннем исключении.
2020-06-04 14:49:25.0514 ERROR В методе: System.Data.Common.DbConnection get_Connection() возникло исключение: Экземпляр ObjectContext был удален и больше не может использоваться в операциях, требующих соединения.
2020-06-04 16:33:06.5028 ERROR В методе: Int32 SaveChanges() возникло исключение: При обновлении записей возникла ошибка. Дополнительные сведения приведены во внутреннем исключении.
2020-06-04 16:33:31.8988 ERROR В методе: Int32 SaveChanges() возникло исключение: При обновлении записей возникла ошибка. Дополнительные сведения приведены во внутреннем исключении.
2020-06-04 16:36:28.1500 ERROR В методе: Int32 SaveChanges() возникло исключение: При обновлении записей возникла ошибка. Дополнительные сведения приведены во внутреннем исключении.
